---
title: "Cutting Taxes, Growing Deficits"
author: "Taylor G. White"
date: "March 7, 2019"
output:
  html_document:
      df_print: tibble
      highlight: tango
      theme: readable
      toc: yes
      toc_depth: 3
      toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
urlcolor: blue    
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Data
```{r, echo = FALSE}

# these datasets are generated in (2)_analyze_US_fiscal_data.r
load('data/US_political_economic_data.rdata')

reg_dat = select(US_wide, Year,  
                 president_party, 
                 dem_congress, 
                 unified_congress, 
                 unified_government, 
                 # house_majority, senate_majority,
                 pct_of_year_in_recession, 
                 recession_year, 
                 contains("GGNLEND"), 
                 contains('gdp_per_capita'),
                 contains('top_tax_rate'), 
                 contains('GGEXP'), contains('GGREV')
                 ) %>% na.omit()


```




# Run regressions

